config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts

  resources :posts do
    resources :tags
  end

  resources :posts do
    resources :comments
  end

  resources :tags

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :comments
  validates :title, :presence => true
  validates :description, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @post = Post.find(params[:post_id])
    @user = User.find(current_user)
    @comment = @post.comments.new(comment_params)
    @comment.user_id = @user.id
    if @comment.save
      respond_to do |format|
        format.html {redirect_to posts_path}
        format.js
      end
    else
      render post_path(@post)
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all
      @tags = Tag.all
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        flash[:alert] = "You Successfully Added A Post"
        redirect_to posts_path
      else
        render :new
      end
    end

    def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
    @tag = Tag.new
  end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        respond_to do |format|
          format.html {redirect_to posts_path}
          format.js
        end
      else
        render :edit
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end



  private
  def post_params
    params.require(:post).permit(:title, :description)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new
  end

  def create
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new(tag_params)
    @post.tags.push(@tag)
    if @tag.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

  def edit
    @post = Post.find(params[:post_id])
    @tag = Tag.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to post_path(@post)
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li>
  <%= comment.body %>
</li>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>" );
$('#comment_body').val('');

app/views/comments/edit.html.erb
<h1>Update Your Comment</h1>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Trav's Blog</a>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>


  <div class="container">
    <div class="container main-container">
      <% if notice %>
        <p id ="flash" class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id ="flash" class="alert alert-danger"><%= alert %></p>
      <% end %>
      <br><br><br>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
  <%= render "layouts/errors", :object => @post %>

  <%= form_for @post, remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
  <% end %>

app/views/posts/_post.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.description %></p>

app/views/posts/edit.html.erb
<h1>Edit Blog Post <%=@post.title %> </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<legend><h1>Blog Posts</h1></legend>

   <% if @posts.any? %>
      <ul>
        <% @posts.each do |post| %>
         <li>
           <%= link_to post.title, post_path(post) %> |
                    <%= link_to "Edit", edit_post_path(post) %> |
                    <%= link_to "Delete", post_path(post),
                          :data => {:confirm => "You sure m8?",
                                  :method => "delete"}%>
         </li>
          <% end %>
       </ul>
   <% else %>
    <p>There Will Be No dancing in Bomont</p>
    <% end %>

    <%= link_to 'Add A Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Add A New Post YO</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Blog-Post Page</h1>
<hr>


<div id="finaledited">  
  <div id="editfeatures">
    <h3><%=@post.title %></h3>
    <%= @post.description %>
  </div>
</div>
  <button class="btn btn-default" id="editorButton">Edit</button>


      <div id="editor">
        <%= render 'form' %>
      </div>
        | <%= link_to 'Delete', post_path(@post),
                                          :data => {:confirm => "You sure m8?",
                                                    :method => "delete"}%>

<h3>Tags: </h3>
<ul>
  <% @post.tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %>  <%= link_to 'edit tag', edit_post_tag_path(@post, tag) %> |
      <%= link_to "Delete", post_tag_path(@post, tag),
                            :data => {:confirm => "Ya sure mate?",
                                      :method => "delete"} %></li>
    <% end %>

</ul>

<h4><%= link_to "Add A Tag", new_post_tag_path(@post) %></h4>


<h3>Comments</h3>
<hr>


    <section id="comments-section">
        <ol id="comments">
          <% @post.comments.each do |comment| %>
            <%= render comment %>
          <% end %>
        </ol>

<% if current_user %>
  <%= form_for [@post, @comment], remote: true do |f| %>
    <%= f.label :comment %>
    <%= f.text_field :body, id: "comment_body" %>
    <%= f.submit %>
  <% end %>
  <% else %>
  <h2>If you'd like to comment please <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Log in", new_user_session_path %> </h2>
  <% end %>

app/views/posts/update.js.erb
$('#editfeatures').html('<%= j render @post %>')
$('#editor').toggle()

app/views/tags/_form.html.erb
<%= render "layouts/errors", :object => @tag %>

<%= form_for [@post, @tag] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render 'form' %>

app/views/tags/new.html.erb
<h1>Add A Tag for <%= @post.title %> </h1>

<%= render 'form' %>

app/views/tags/show.html.erb
<h1>Blog posts with the tag <em><%= @tag.name %></em></h1>

<% @tag.posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

<br><br>

<%= link_to "Back to Posts", posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>